name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Check Gradle execute permissions 
      - name: Enables execute for Gradle
        run: chmod +x gradlew

      # Runs the Gradle build task
      - name: Run the Gradle Build
        run: ./gradlew build
        
      # Builds a 'fat' jar file with the dependencies from Gradle
      - name: Archive Jar with Dependencies
        uses: actions/upload-artifact@v4.4.2
        with:
          name: Jar with Dependencies
          path: build/libs

      # Builds a zip file with JUnit test report in it    
      - name: Archive test report
        uses: actions/upload-artifact@v4.4.2
        with:
          name: Test report
          path: build/reports/tests/test

      # Runs the Gradle dokkaHtml task
      - name: Dokka with Gradle
        run: ./gradlew dokkaHtml
      
      # Builds a zip file with the KDoc generated website in it 
      - name: Archive KDoc Documentation
        uses: actions/upload-artifact@v4.4.2
        with:
          name: KDoc Documentation Site
          path: build/dokka/html
